version: "3.9"

services:
  db:
    image: postgres:15
    container_name: admission_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Prabhas@1234
      POSTGRES_DB: admission_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: admission_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:Prabhas%401234@db:5432/admission_db
    restart: always

volumes:
  postgres_data:
